// components/NavBar.tsx
"use client";

import { scrollToSection } from "@/lib/scrollToSection";

const navLinks = [
  { label: "活動資訊", sectionId: "intro" },
  { label: "工作簡介", sectionId: "seat" },
  { label: "分類帽", sectionId: "question" },
];

export default function NavBar() {
  return (
    <header className="fixed top-0 left-0 right-0 z-50 h-[var(--header-height)] bg-white border-b border-gray-100 sm:bg-white/95 sm:backdrop-blur-md">
      <div className="section-container h-full">
        <div className="flex items-center justify-between h-full">
          <button
            type="button"
            onClick={() => scrollToSection("intro")}
            className="flex flex-col items-start text-left group"
          >
            <span className="text-xs text-hotline font-semibold tracking-widest uppercase">
              Hotline 2026
            </span>
            <span className="font-mantou text-lg sm:text-xl text-gray-900 group-hover:text-hotline transition-colors">
              熱線募款感恩會
            </span>
          </button>

          <nav>
            <ul className="flex items-center gap-4 sm:gap-8">
              {navLinks.map(({ label, sectionId }) => (
                <li key={sectionId}>
                  <a
                    href={`#${sectionId}`}
                    onClick={(e) => {
                      e.preventDefault();
                      scrollToSection(sectionId);
                    }}
                    className="nav-link hidden sm:inline-block py-2 font-mantou"
                  >
                    {label}
                  </a>
                  <a
                    href={`#${sectionId}`}
                    onClick={(e) => {
                      e.preventDefault();
                      scrollToSection(sectionId);
                    }}
                    className="sm:hidden text-sm font-medium text-gray-700 hover:text-hotline py-2 font-mantou"
                  >
                    {label.slice(0, 2)}
                  </a>
                </li>
              ))}
            </ul>
          </nav>
        </div>
      </div>
    </header>
  );
}

// src/components/NavBar.vue
<template>
  <nav class="fixed top-0 left-0 right-0 z-50 bg-white/90 backdrop-blur-sm shadow-lg">
    <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-center items-center h-14 sm:h-16">
        <ul class="flex space-x-4 sm:space-x-6 md:space-x-8">
          <li>
            <a
              href="#intro"
              @click="scrollToSection('intro')"
              class="nav-link font-mantou text-sm sm:text-base md:text-lg font-medium text-gray-800 hover:text-[#ff98b3] transition-colors duration-300 cursor-pointer"
            >
              活動資訊
            </a>
          </li>
          <li>
            <a
              href="#seat"
              @click="scrollToSection('seat')"
              class="nav-link font-mantou text-sm sm:text-base md:text-lg font-medium text-gray-800 hover:text-[#ff98b3] transition-colors duration-300 cursor-pointer"
            >
              工作簡介
            </a>
          </li>
          <li>
            <a
              href="#question"
              @click="scrollToSection('question')"
              class="nav-link font-mantou text-sm sm:text-base md:text-lg font-medium text-gray-800 hover:text-[#ff98b3] transition-colors duration-300 cursor-pointer"
            >
              分類帽
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
const scrollToSection = (sectionId: string) => {
  const element = document.getElementById(sectionId);
  if (element) {
    const navbarHeight = window.innerWidth < 640 ? 56 : 64; // Responsive navbar height
    const elementPosition = element.offsetTop - navbarHeight - 20; // Extra padding for better positioning
    
    // Custom smooth scroll with faster timing
    const startPosition = window.pageYOffset;
    const distance = elementPosition - startPosition;
    const duration = Math.min(800, Math.abs(distance) * 0.5); // Max 800ms, adaptive based on distance
    let startTime: number | null = null;

    const easeInOutCubic = (t: number): number => {
      return t < 0.5 ? 4 * t * t * t : (t - 1) * (2 * t - 2) * (2 * t - 2) + 1;
    };

    const animateScroll = (currentTime: number) => {
      if (startTime === null) startTime = currentTime;
      const timeElapsed = currentTime - startTime;
      const progress = Math.min(timeElapsed / duration, 1);
      const ease = easeInOutCubic(progress);
      
      window.scrollTo(0, startPosition + distance * ease);
      
      if (progress < 1) {
        requestAnimationFrame(animateScroll);
      }
    };

    requestAnimationFrame(animateScroll);
  }
};
</script>

<style scoped>
.nav-link {
  position: relative;
}

.nav-link::after {
  content: '';
  position: absolute;
  width: 0;
  height: 2px;
  bottom: -4px;
  left: 50%;
  background-color: #ff98b3;
  transition: all 0.3s ease-in-out;
  transform: translateX(-50%);
}

.nav-link:hover::after {
  width: 100%;
}
</style>
